"""Detect all tables

Revision ID: 35f46da66c92
Revises: 14dc6006f04a
Create Date: 2025-05-06 19:32:10.160166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35f46da66c92'
down_revision = '14dc6006f04a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landlords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('property_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_type_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('landlord_property_type',
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('property_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.ForeignKeyConstraint(['property_type_id'], ['property_types.id'], ),
    sa.PrimaryKeyConstraint('landlord_id', 'property_type_id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('telephone', sa.String(length=12), nullable=False),
    sa.Column('occupation', sa.String(length=50), nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rental_buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('starting_date', sa.Date(), nullable=False),
    sa.Column('ending_date', sa.Date(), nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('property_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.ForeignKeyConstraint(['property_type_id'], ['property_types.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rental_buildings')
    op.drop_table('tenants')
    op.drop_table('landlord_property_type')
    op.drop_table('property_types')
    op.drop_table('landlords')
    # ### end Alembic commands ###
