"""Initial migration including payments table

Revision ID: f8dc96c4d002
Revises: 
Create Date: 2025-05-28 13:41:46.879122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8dc96c4d002'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landlords',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('property_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_type_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('landlord_property_type',
    sa.Column('landlord_id', sa.Integer(), nullable=False),
    sa.Column('property_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.ForeignKeyConstraint(['property_type_id'], ['property_types.id'], ),
    sa.PrimaryKeyConstraint('landlord_id', 'property_type_id')
    )
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('telephone', sa.String(length=12), nullable=False),
    sa.Column('occupation', sa.String(length=50), nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rental_buildings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('starting_date', sa.Date(), nullable=False),
    sa.Column('ending_date', sa.Date(), nullable=False),
    sa.Column('landlord_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('property_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ),
    sa.ForeignKeyConstraint(['property_type_id'], ['property_types.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monthly_price', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('payment_status', sa.Boolean(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('payment_period', sa.String(length=7), nullable=False),
    sa.Column('rental_building_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rental_building_id'], ['rental_buildings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('rental_buildings')
    op.drop_table('tenants')
    op.drop_table('landlord_property_type')
    op.drop_table('property_types')
    op.drop_table('landlords')
    # ### end Alembic commands ###
